"""
Module containing function to estimate fitness for amino acids with two or more codons.
Simpler implementation based on scipy.optimize.minimize
"""

import itertools
from typing import List, Dict, Tuple, Callable
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import minimize
from scipy import stats


def extract_unique_codons(codon_changes: List[Tuple[str, float]]) -> List[str]:
    """
    Extract unique codons from a list of codon changes from CodonPairs data.
    """
    unique_codons = set()
    for change, _ in codon_changes:
        start, end = change.split('>')
        unique_codons.add(start)
        unique_codons.add(end)

    return sorted(list(unique_codons))


def import_from_codonpair(inputfile: str) -> Dict[str, Tuple[List[Tuple[str, float]], List[str]]]:
    """
    Import codon pair data from a file and extract unique codons for each amino acid.
    """

    codon_data: Dict[str, Tuple[List[Tuple[str, float]], List[str]]] = {}

    try:
        with open(inputfile, 'r', encoding='utf-8') as infile:
            for line in infile:
                if line.startswith("Codon_pair"):
                    continue
                if len(line.split()) == 8 and ">" in line.split()[0]:
                    parts = line.split()
                    codon_change = parts[0]
                    amino_acid = parts[1]
                    try:
                        two_ns = float(parts[7])
                    except ValueError:
                        continue  # Skip lines where conversion to float fails

                    # Add the codon change to the dictionary
                    if amino_acid not in codon_data:
                        codon_data[amino_acid] = ([], [])

                    codon_data[amino_acid][0].append((codon_change, two_ns))

        # After processing all lines, calculate unique codons for each amino acid
        for amino_acid, (changes, _) in codon_data.items():
            # print(changes)
            unique_codons = extract_unique_codons(changes)
            codon_data[amino_acid] = (changes, unique_codons)

    except FileNotFoundError:
        print(f"Error: File '{inputfile}' not found.")
    except IOError:
        print(f"Error: Could not read file '{inputfile}'.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

    return codon_data


def extract_zeros_from_matrix(m: np.ndarray) -> List[Tuple[int, int]]:
    """
    It extracts the positions of zeros in a matrix.
    Return a List of Tuples (i, j) where m[i, j] = 0

    It is going to be use to get the m[i, j] = 0 from the observed matrix containing
    selection coefficietns 2Ns. Zeros are structural in this case:
    - all m[i, j] = 0 if i == j
    - for non valid codon pairs.
    
    The positions (i,j) extracted here are going 
    to be impute the zeros in matrix generated by the model.
    """

    # Find indices of zeros
    zero_indices = np.where(m == 0)

    # Convert to a list of tuples for easier handling
    zero_positions = list(zip(zero_indices[0], zero_indices[1]))

    return zero_positions


def impute_zeros_in_matrix(
    m: np.ndarray,
    zero_positions: List[Tuple[int, int]]
) -> np.ndarray:
    """
    It imputes the zeros in a matrix m at the positions specified in zero_positions
    """

    # Create a copy of the original matrix
    m_imputed = m.copy()

    # Impute the values from the original matrix into the new matrix at zero positions
    for i, j in zero_positions:
        m_imputed[i, j] = 0

    return m_imputed


def create_matrix_from_codon_changes(
        codon_changes: List[Tuple[str, float]],
        codons: List[str]
        ) -> np.ndarray[np.float64]:
    """
    Function to make n x n matrix of observed codon changes 2Ns from CodonPair data 
    The returned matrix of obseved 2Ns values is based on the codon pairs in codon_changes
    and the list of unique codons in codons.
    The n x n matrix will be compatible with downstream linear regression model.
    """

    # Create a 4x4 matrix of zeros
    m = np.zeros((len(codons), len(codons)))

    # Create a dictionary to map codon pairs to their 2Ns values
    codon_dict = {pair: value for pair, value in codon_changes}

    # Populate the matrix
    for i, from_codon in enumerate(codons):
        for j, to_codon in enumerate(codons):
            if i != j:  # Skip diagonal elements
                pair = f"{from_codon}>{to_codon}"
                reverse_pair = f"{to_codon}>{from_codon}"

                if pair in codon_dict:
                    m[i][j] = codon_dict[pair]
                elif reverse_pair in codon_dict:
                    m[i][j] = -codon_dict[reverse_pair]
                # If neither pair is in the dictionary, it remains 0

    # Extract the indexes of structural zeros
    zero_positions = extract_zeros_from_matrix(m)

    # Return the matrix
    return {
        'm_obs': m,
        'zero_positions': zero_positions
    }


def build_b_vector(
    m: np.ndarray,
    zero_positions: List[Tuple[int, int]]
) -> np.ndarray:
    """
    Build the vector b for the linear model Ax = b,
    using only the upper triangular part of the m matrix.
    
    :param m: The matrix of codon changes
    :return: vector b
    """

    num_codons = m.shape[0]
    pairs = list(itertools.combinations(range(num_codons), 2))

    # Extract only upper triangular values without structural zeros
    # b = np.array([m[i, j] for i, j in pairs])
    b = np.array([m[i, j] for i, j in pairs if (i, j) not in zero_positions])

    # Return the vector
    return b


def create_matrix_from_fitnesses(
    fitnesses: np.ndarray,
    zero_positions: List[Tuple[int, int]],
    ne: int = 1
) -> np.ndarray:
    """
    Create a matrix from a vector of relative fitnesses (vector of p's).
    This is the heart of the method. 
    Convert the vector p to a list and insert 1 at the beginning because 
    the first codon fitness is the reference set to the value 1.

    The returned matrix m contains deduced selection coefficients 2Ns 
    from the fitnesses vector.
    """

    # Convert p to a list and insert 1 at the beginning
    p = np.array([1] + list(fitnesses))
    if ne != 1:
        p = 2 * ne * p

    # The the number of codons
    ncodons = len(p)

    # Create an n x n matrix filled with zeros
    m = np.zeros((ncodons, ncodons))

    # Fill the matrix according to the specified rules
    for i in range(ncodons):
        for j in range(ncodons):
            if i != j:
                m[i, j] = p[i] - p[j]
                m[j, i] = p[j] - p[i]

    # Impute m[i, j] = 0 back to the inferred matrix
    # Maybe it is not necessary given the way zeros in observed 2Ns matrix are handled.
    m_zero_imputed = impute_zeros_in_matrix(m, zero_positions)

    return m_zero_imputed


def lsqdistance(fitnesses: List[float],
                m_obs: np.ndarray,
                zero_positions: List[Tuple[int, int]],
                ne: int = 1) -> np.ndarray:
    """
    Residual function to be used with scipy.optimize.least_squares
    It requires the matrix m_obs containing the observed 2Ns' from CodonPair,
    the list of fitness values (starting values), and the effective population 
    size (default = 1).
    """

    # Obtain the mxm matrix derived from the p vector of fitness
    m_deduced = create_matrix_from_fitnesses(fitnesses=fitnesses,
                                          zero_positions=zero_positions,
                                          ne=ne)

    # return np.sum((m - datam)**2)
    # ignore cells where datam is 0,  as occurs with 6-fold amino acids
    return np.sum((m_deduced - m_obs)**2 * (m_obs != 0))


def calculate_errors_square(
    b_obs: np.ndarray,
    b_pred: np.ndarray
) -> Tuple[float, float]:
    """
    Calculates the relative error squared and normalized squared error
    when there is zero in the predicted b vector. It circunvents possibilities
    of zeros other than zeros because of the 6-codon amino acids (likely generated
    for pods simulations).
    """
    relative_error_squared = 0
    normalized_squared_error = 0

    for i, obs in enumerate(b_obs):
        if b_pred[i] == 0:
            continue

        relative_error_squared += ((b_obs[i] - b_pred[i]) / b_pred[i]) ** 2
        normalized_squared_error += ((b_obs[i] - b_pred[i]) ** 2) / b_pred[i]

    return abs(relative_error_squared), abs(normalized_squared_error)


def solve_for_fitness(
    residuals: Callable[[List[float], np.ndarray, int], np.ndarray],
    m_obs: np.ndarray,
    initial_guess: List[float],
    zero_positions: List[Tuple[int, int]],
    ne: int = 1
) -> np.ndarray:
    """
    Solve for fitness values using scipy.optimize.minimize. 
    How the optimization is performed depends on the residuals function.
    The residual function could be simply one that finds the minimum differences 
    between the observed 2Ns and the deduced 2Ns from the guessed fitness values.
    The optimization uses the Sequential Least Squares Programming (SLSQP) algorithm.
    
    The function residuals is called with the initial guess and the observed 2Ns matrix.
    Initial guess excluding the reference codon fitness, which is set to 1.
    """
    
    # Constraints: all fitness values must be positive
    constrainsts = ({'type': 'ineq', 'fun': lambda x: x})

    # Perform optimization
    optimized_results = minimize(residuals,
                                 initial_guess,
                                 args=(m_obs, zero_positions, 1),
                                 method='SLSQP',
                                 constraints=constrainsts)

    # Calculate the predicted selection coefficients matrix
    m_pred = create_matrix_from_fitnesses(optimized_results.x, zero_positions, ne)

    # Extract the optimized fitness values
    p_vector = np.concatenate(([1], optimized_results.x))

    # Extract the upper values of the observed and predicted 2Ns matrices
    # Called here b vector to aling with the linear algebra notation.
    b_obs = build_b_vector(m_obs, zero_positions)
    b_pred = build_b_vector(m_pred, zero_positions)

    # # Calculate the error metrics
    # relative_error_squared = abs(np.sum(((b_obs - b_pred) / b_pred)**2))
    # normalized_squared_error = abs(np.sum(((b_obs - b_pred)**2) / b_pred))

    relative_error_squared, normalized_squared_error = calculate_errors_square(b_obs, b_pred)

    # Calculate the correlation coefficient
    correlation_coefficient, p_value_corr = stats.pearsonr(b_obs, b_pred)

    return {
        "predicted_matrix": m_pred,
        "relative_fitness": p_vector,
        "observed_selection_coefficients": b_obs,
        "predicted_selection_coefficients": b_pred,
        "relative_error_square": relative_error_squared,
        "normalized_squared_error": normalized_squared_error,
        "correlation_coefficient": correlation_coefficient,
        "p_value_correlation": p_value_corr
    }


def construct_full_matrix(b: np.ndarray, n: int) -> np.ndarray:
    """
    Construct a full nxn matrix of predicted b values from the vector b.
    
    :param b: Vector of predicted b values from A.dot(x)
    :return: Full nxn matrix of predicted b values
    """

    # Create a 4x4 matrix of zeros
    m = np.zeros((n, n))

    # Fill the upper triangle of the matrix
    idx = 0
    for i in range(n):
        for j in range(i+1, n):
            m[i, j] = b[idx]
            m[j, i] = -b[idx]  # Fill lower triangle with negative values
            idx += 1

    return m


def permutation_test(
        m_obs: np.ndarray,
        obs_test_statistic: float,
        residuals: Callable[[List[float], np.ndarray, int], np.ndarray],
        initial_guess: List[float],
        zero_positions: List[Tuple[int, int]],
        test_statistic: str = 'normalized_squared_error',
        num_permutations: int = 1000) -> Tuple[float, np.ndarray, float]:
    """
    Function to perform a permutation test on the fitness model.
    For the moment, only a normalized error squared is used as the metric.
    It takes the matrix of observations m min and max and sample uniformly from this range.
    """

    # Get the number of rows in the matrix
    n = m_obs.shape[0]

    # Get the pairs of indices from the matrix (without the i=j indices)
    m_pairs = list(itertools.permutations(range(n), 2))

    # Get the min and max from the matrix m:
    m_flat = np.array([m_obs[i, j] for i, j in m_pairs if (i, j) not in zero_positions])

    m_min = np.min(m_flat)
    m_max = np.max(m_flat)  # or (-1) * m_min?

    # Get the number of b permuted elements:
    # This is number of elements in the matrix upper triangle.
    m_upper_len = int((n * (n - 1)) / 2)

    # Initialize the vector of permutations
    permutations = np.zeros(num_permutations)

    for i in range(num_permutations):

        # Sample uniformly from m_min to m_max
        b_perm = np.random.uniform(m_min, m_max, m_upper_len)

        # Construct the full predicted matrix
        m_perm = construct_full_matrix(b_perm, n)

        # Impute zeros in the matrix
        m_perm = impute_zeros_in_matrix(m_perm, zero_positions)

        # Solve for fitness values
        solved_perm = solve_for_fitness(residuals, m_perm, initial_guess, zero_positions)

        # This take the absolute value of the test statistic
        permutations[i] = solved_perm[test_statistic]

    # Calculate the p-values
    p_value_lwr = np.sum(permutations < obs_test_statistic) / num_permutations
    p_value_leq = np.sum(permutations <= obs_test_statistic) / num_permutations
    p_value = (np.random.uniform(p_value_lwr, p_value_leq, 1)).tolist()[0]

    # Count the number of permutation < 0:
    prob_neg = np.sum(permutations < 0) / num_permutations

    return {
        'p_value_lwr': p_value_lwr, 
        'p_value_leq': p_value_leq, 
        'p_value': p_value,
        'permutations': permutations,
        'prob_neg': prob_neg
    }


def simulate_and_analyze_pods(
    m_obs: np.ndarray,
    residuals: Callable[[List[float], np.ndarray, int], np.ndarray],
    initial_guess: List[float],
    zero_positions: List[Tuple[int, int]],
    test_statistic: str = 'normalized_squared_error',
    num_permutations: int = 1000
) -> np.ndarray:
    """
    Proof of concept: this functions takes the m_obs matrix, sample 
    uniformly from the max and min, and use the sampled values to create 
    a new observation matrix (a pod).
    
    With the pod all the steps are repeated: 
    - solve for fitness, 
    - calculate the test statistic, and 
    - calculate the p-value.
    """

    # Get the number of rows in the matrix
    n = m_obs.shape[0]

    # Get the pairs of indices from the matrix (without the i=j indices)
    m_pairs = list(itertools.permutations(range(n), 2))

    # Get the min and max from the matrix m:
    m_flat = np.array([m_obs[i, j] for i, j in m_pairs if (i, j) not in zero_positions])

    m_min = np.min(m_flat)
    m_max = np.max(m_flat)  # or (-1) * m_min?

    # Get the number of b permuted elements:
    # This is number of elements in the matrix upper triangle.
    m_upper_len = int((n * (n - 1)) / 2)
    
    # Sample uniformly from m_min to m_max
    b_pod = np.random.uniform(m_min, m_max, m_upper_len)

    # Construct the full predicted matrix
    m_pod = construct_full_matrix(b_pod, n)

    # Impute zeros in the matrix
    m_pod = impute_zeros_in_matrix(m_pod, zero_positions)

    # Solve for fitness values
    solved_pod = solve_for_fitness(residuals, m_pod, initial_guess, zero_positions)

    # Obtain p-value with permutation test
    perm_test = permutation_test(
        m_pod,
        solved_pod[test_statistic],
        residuals,
        initial_guess,
        zero_positions,
        test_statistic,
        num_permutations
    )

    return perm_test['p_value']


def histograma_plot(
        permuted_data: np.ndarray,
        obs_test_statistic: float,
        title: str = "Histograma Plot") -> None:
    """
    Plot a histogram distribution plot comparing 
    the permuted data to a theoretical Chi-square distribution.

    Parameters:
    permuted_data (array-like): Array of permuted normalized squared errors.
    obs_test_statistic (float): Observed test statistic.
    title (str): Title for the combined plot.
    """

    # Create the histogram
    plt.figure(figsize=(10, 6))
    plt.hist(permuted_data, bins=20, density=True, alpha=0.6, color='b')
    plt.axvline(obs_test_statistic, color='r', linestyle='dashed', linewidth=2)

    # Add labels and title
    plt.xlabel('Normalized Squared Error', fontsize=14)
    plt.ylabel('Density', fontsize=14)
    plt.title(title)
    plt.grid(False)
    plt.show()


def fisher_method(p_values: List[float]) -> Tuple[float, float]:
    """
    Perform Fisher's Methdo to calculate the chi-squared statistic and p-value.
    It is the original meta-analysis method for a list of p-values from independent tests.

    Parameters:
    p_values (list): List of p-values.

    Returns:
    Tuple of chi-squared statistic and p-value.
    """

    # calculate the chi-squared statistic
    df = 2*len(p_values)
    test_statistic = -2 * np.sum(np.log(p_values))

    # calculate the p-value
    p_value = 1 - stats.chi2.cdf(test_statistic, df)

    return test_statistic, p_value


def main() -> None:

    # Input data
    codon_changes = [
        ('CCT>CCC', 0.129),
        ('CCA>CCT', -0.542),
        ('CCT>CCG', 0.646),
        ('CCA>CCC', -0.155),
        ('CCG>CCC', 0.087),
        ('CCA>CCG', -0.167)
    ]

    # Define the codons in order
    # Here you can define a different reference codon by setting it to index 0
    codons = ['CCA', 'CCC', 'CCG', 'CCT']

    # Create the m x m matrix of codon changes 2Ns'.
    data = create_matrix_from_codon_changes(codon_changes, codons)

    # List with initial guesses for relative fitnesses
    initial_guess = [1, 1, 1]

    # Solve for fitness values
    solved = solve_for_fitness(lsqdistance, data['m_obs'], initial_guess, data['zero_positions'])

    # Calculate p-valeu with permutation test
    statistical_test = permutation_test(
        data['m_obs'],
        solved['normalized_squared_error'],
        lsqdistance,
        initial_guess,
        zero_positions=data['zero_positions'],
        test_statistic='normalized_squared_error',
        num_permutations=1000
    )

    print(statistical_test)

    # Simulate and analyze pods for proof of concept
    num_pods = 0
    pods_pvalues = []
    while num_pods < 1001:
        print(f"Running simulation #: {num_pods}")
        simulated_pvalues = simulate_and_analyze_pods(data['m_obs'],
                                                      lsqdistance,
                                                      initial_guess,
                                                      zero_positions=data['zero_positions'],
                                                      test_statistic='normalized_squared_error',
                                                      num_permutations=1000
                                                      )
        pods_pvalues.append(simulated_pvalues)
        num_pods += 1

    plt.hist(pods_pvalues, bins=5)
    plt.show()


if __name__ == '__main__':
    main()
